name: pomodoro
description: "App Pomodoro."

publish_to: 'none'

version: 4.1.0+7

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.3
  just_audio: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "asset/tomate.png"
  adaptive_icon_background: '#314F4F'
  adaptive_icon_foreground: 'asset/1024.png'
  min_sdk_android: 21

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
  
